"use client";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { type FormEvent,useEffect,useRef,useState } from "react";
import { Search,UserRound,X,MoreVertical,Home,BookOpen,GraduationCap,Newspaper,CalendarDays,Scale,FileText,MapPin,Phone,ShieldCheck,LockKeyhole,BookMarked } from "lucide-react";
import { EsppMobileThemeToggle } from "@/components/espp-mobile-theme-toggle";
const links=[{href:"/",label:"Início",Icon:Home},{href:"/institucional",label:"Institucional",Icon:GraduationCap},{href:"/localizacao",label:"Localização",Icon:MapPin},{href:"/formacao",label:"Formação",Icon:BookOpen},{href:"/cursos",label:"Cursos",Icon:GraduationCap},{href:"/noticias",label:"Notícias",Icon:Newspaper},{href:"/eventos",label:"Eventos",Icon:CalendarDays},{href:"/regimento-interno",label:"Regimento Interno",Icon:BookMarked},{href:"/atos-normativos",label:"Atos Normativos",Icon:Scale},{href:"/documentos",label:"Documentos Institucionais",Icon:FileText},{href:"/contato",label:"Contato",Icon:Phone},{href:"/lgpd",label:"LGPD",Icon:ShieldCheck},{href:"/admin",label:"Acesso restrito",Icon:LockKeyhole}] as const;
export function EsppMobileHeader(){const router=useRouter();const[busca,setBusca]=useState(false);const[mais,setMais]=useState(false);const[q,setQ]=useState("");const input=useRef<HTMLInputElement>(null);useEffect(()=>{const aberto=busca||mais;if(busca)requestAnimationFrame(()=>input.current?.focus());document.body.style.overflow=aberto?"hidden":"";return()=>{document.body.style.overflow=""}},[busca,mais]);function submit(e:FormEvent){e.preventDefault();const termo=q.trim();if(!termo)return;setBusca(false);router.push(`/busca?q=${encodeURIComponent(termo)}`)}
return <><header className="espp-mobile-header fixed inset-x-0 top-0 z-[70] border-b border-white/10 bg-[#171d27]/96 pt-[env(safe-area-inset-top)] text-white shadow-sm backdrop-blur-xl md:hidden"><div className="flex h-16 min-w-0 items-center px-3"><Link href="/" aria-label="ESPP — início" className="relative block h-13 min-w-0 flex-1 overflow-hidden"><Image src="/images/logo-espp-white.png" alt="ESPP" fill sizes="120px" className="espp-logo-white object-contain object-left" priority/><Image src="/images/logo-espp.png" alt="" aria-hidden="true" fill sizes="120px" className="espp-logo-color hidden object-contain object-left" priority/></Link><div className="ml-2 flex shrink-0 items-center gap-1"><button type="button" onClick={()=>setBusca(true)} aria-label="Buscar" className="espp-mobile-action inline-flex size-9 items-center justify-center rounded-xl text-white/60"><Search className="size-[1.05rem]"/></button><button type="button" onClick={()=>setMais(true)} aria-label="Mais opções" className="espp-mobile-action inline-flex size-9 items-center justify-center rounded-xl text-white/60"><MoreVertical className="size-5"/></button><Link href="/admin" aria-label="Acesso restrito" className="inline-flex size-9 items-center justify-center rounded-full border border-[#f5c400]/35 bg-[#f5c400]/12 text-[#f5c400]"><UserRound className="size-4"/></Link></div></div><style jsx global>{`:root[data-mobile-theme="light"] .espp-mobile-header .espp-logo-white{display:none!important}:root[data-mobile-theme="light"] .espp-mobile-header .espp-logo-color{display:block!important}`}</style></header>
{busca?<div className="fixed inset-0 z-[100] flex items-start justify-center bg-[#071522]/55 px-4 pt-[max(5rem,env(safe-area-inset-top))] backdrop-blur-md md:hidden" onMouseDown={e=>{if(e.target===e.currentTarget)setBusca(false)}}><div className="w-full max-w-md rounded-[1.35rem] border border-white/55 bg-white/90 p-4 shadow-2xl backdrop-blur-2xl"><div className="mb-3 flex items-center justify-between"><div><p className="text-[.62rem] font-black tracking-[.14em] text-[#0b3157]/55 uppercase">ESPP</p><h2 className="text-lg font-extrabold text-[#071522]">Buscar</h2></div><button type="button" onClick={()=>setBusca(false)} className="inline-flex size-9 items-center justify-center rounded-xl bg-[#071522]/5"><X className="size-4"/></button></div><form onSubmit={submit} className="flex items-center gap-2 rounded-2xl border border-[#0b3157]/10 bg-white/80 p-1.5"><Search className="ml-2 size-4 text-[#0b3157]/50"/><input ref={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="O que você procura?" className="min-w-0 flex-1 bg-transparent py-2.5 text-sm text-[#071522] outline-none"/><button disabled={!q.trim()} className="rounded-xl bg-[#0b3157] px-3.5 py-2.5 text-xs font-extrabold text-white disabled:opacity-40">Buscar</button></form></div></div>:null}
{mais?<div className="fixed inset-0 z-[100] bg-[#071522]/45 backdrop-blur-sm md:hidden" onMouseDown={e=>{if(e.target===e.currentTarget)setMais(false)}}><aside role="dialog" aria-modal="true" aria-label="Navegação" className="absolute inset-y-0 right-0 flex w-[min(88vw,22rem)] flex-col border-l border-white/55 bg-white/92 px-4 pb-[max(1rem,env(safe-area-inset-bottom))] pt-[max(1rem,env(safe-area-inset-top))] shadow-[-18px_0_55px_rgba(7,21,34,.24)] backdrop-blur-2xl animate-[slideInRight_.22s_ease-out]"><div className="mb-4 flex items-center justify-between"><div><p className="text-[.62rem] font-black tracking-[.14em] text-[#0b3157]/55 uppercase">ESPP</p><h2 className="text-lg font-extrabold text-[#071522]">Navegação</h2></div><button type="button" onClick={()=>setMais(false)} className="inline-flex size-9 items-center justify-center rounded-xl bg-[#071522]/5"><X className="size-4"/></button></div><div className="mb-4 rounded-2xl border border-[#0b3157]/10 bg-white/70 p-3"><p className="mb-2 text-[.62rem] font-black tracking-[.12em] text-[#0b3157]/55 uppercase">Aparência</p><EsppMobileThemeToggle menu /></div><nav className="grid grid-cols-2 gap-2 overflow-y-auto">{links.map(({href,label,Icon})=><Link key={href} href={href} onClick={()=>setMais(false)} className="flex min-h-[4.8rem] min-w-0 flex-col items-center justify-center gap-1.5 rounded-xl bg-[#eef3f7]/80 p-2 text-center text-[.68rem] font-bold text-[#334155]"><Icon className="size-4 text-[#0b3157]"/><span>{label}</span></Link>)}</nav></aside><style jsx global>{`@keyframes slideInRight{from{transform:translateX(100%)}to{transform:translateX(0)}}`}</style></div>:null}</>}
