"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Accessibility, ChevronDown, Contrast, Menu, Search, X } from "lucide-react";
import { nav, site, topbar } from "@/content/site";
import { Icon } from "@/components/ui/icon";
import { ConfigurableBrandImage } from "@/components/configurable-brand-image";

type TamanhoFonte = "sm" | "md" | "lg";
const ESCALAS_FONTE: Record<TamanhoFonte, string> = { sm: "93.75%", md: "100%", lg: "112.5%" };
const CHAVE_FONTE = "espp-font-size";
const CHAVE_CONTRASTE = "espp-contraste";

export function SiteHeader() {
  const [aberto, setAberto] = useState(false), [rolou, setRolou] = useState(false), [fonte, setFonte] = useState<TamanhoFonte>("md"), [contraste, setContraste] = useState(false), [submenu, setSubmenu] = useState<string | null>(null);
  const pathname = usePathname();
  useEffect(()=>{const f=()=>setRolou(scrollY>8);f();addEventListener("scroll",f,{passive:true});return()=>removeEventListener("scroll",f)},[]);
  useEffect(()=>{document.body.style.overflow=aberto?"hidden":"";return()=>{document.body.style.overflow=""}},[aberto]);
  useEffect(()=>setSubmenu(null),[pathname]);
  useEffect(()=>{if(!submenu)return;const k=(e:KeyboardEvent)=>{if(e.key==="Escape")setSubmenu(null)},m=(e:MouseEvent)=>{if(!(e.target as Element|null)?.closest("[data-submenu]"))setSubmenu(null)};document.addEventListener("keydown",k);document.addEventListener("mousedown",m);return()=>{document.removeEventListener("keydown",k);document.removeEventListener("mousedown",m)}},[submenu]);
  useEffect(()=>{const f=localStorage.getItem(CHAVE_FONTE) as TamanhoFonte|null;if(f&&f in ESCALAS_FONTE)setFonte(f);setContraste(localStorage.getItem(CHAVE_CONTRASTE)==="alto")},[]);
  function aplicarFonte(v:TamanhoFonte){setFonte(v);document.documentElement.style.fontSize=ESCALAS_FONTE[v];localStorage.setItem(CHAVE_FONTE,v)}
  function alternarContraste(){const n=!contraste;setContraste(n);if(n){document.documentElement.setAttribute("data-contrast","alto");localStorage.setItem(CHAVE_CONTRASTE,"alto")}else{document.documentElement.removeAttribute("data-contrast");localStorage.removeItem(CHAVE_CONTRASTE)}}
  return <header className={`fixed inset-x-0 top-0 z-50 transition-shadow duration-300 ${rolou||aberto?"shadow-md":""}`}>
    <div className="bg-gov-blue"><div className="container-espp flex h-7 items-center justify-between gap-4 overflow-x-auto text-[0.65rem]"><a href={topbar.href} target="_blank" rel="noopener noreferrer" className="shrink-0 font-bold tracking-wide text-gold-500">{topbar.label}</a><div className="flex shrink-0 items-center gap-3 text-white/90"><div className="flex items-center gap-1" role="group" aria-label="Tamanho da fonte">{(["sm","md","lg"] as TamanhoFonte[]).map((v,i)=><button key={v} type="button" onClick={()=>aplicarFonte(v)} aria-pressed={fonte===v} className={`px-1 py-0.5 font-bold text-white ${i===0?"text-[.65rem]":i===1?"text-[.75rem]":"text-[.85rem]"} ${fonte===v?"underline":""}`}>{i===0?"A-":i===1?"A":"A+"}</button>)}</div><button type="button" onClick={alternarContraste} className="flex items-center gap-1.5 px-1.5 py-0.5 font-medium text-white"><Contrast className="size-3.5"/><span className="hidden sm:inline">Alto contraste</span></button><Link href="/acessibilidade" className="flex items-center gap-1.5 px-1.5 py-0.5 font-medium text-white"><Accessibility className="size-3.5"/><span className="hidden sm:inline">Acessibilidade</span></Link><Link href="/mapa-do-site" className="hidden px-1.5 py-0.5 font-medium text-white sm:inline">Mapa do site</Link></div></div></div>
    <div className="border-b border-ink-200 bg-white"><div className="container-espp flex h-[7.1rem] items-center justify-between gap-8"><Link href="/" className="flex min-w-0 items-center gap-3" aria-label={`${site.nome} — início`}><span className="flex min-w-0 items-center"><ConfigurableBrandImage area="site" fallbackLight="/images/logo-go-espp.png" fallbackDark="/images/logo-go-espp-branca.png" alt="Estado de Goiás e Escola Superior de Polícia Penal" className="h-[6.4rem] w-auto max-w-[min(72vw,58rem)] object-contain object-left"/></span></Link><div className="flex items-center gap-3"><form action="/busca" method="get" role="search" className="hidden w-[22.5rem] items-center lg:flex"><input name="q" type="search" aria-label="Buscar no site" placeholder="O que você procura?" className="min-w-0 flex-1 rounded-l-sm border border-ink-300 bg-white px-3 py-2.5 text-sm text-ink-900 outline-none placeholder:text-ink-400 focus:border-gov-blue"/><button type="submit" className="ml-1 flex items-center justify-center rounded-sm bg-gov-blue px-5 py-2.5 text-sm font-bold text-white"><Search className="mr-2 size-4"/>Buscar</button></form><button type="button" onClick={()=>setAberto(v=>!v)} aria-expanded={aberto} className="inline-flex size-11 shrink-0 items-center justify-center rounded-md border border-ink-300 text-ink-900 xl:hidden">{aberto?<X className="size-5"/>:<Menu className="size-5"/>}</button></div></div></div>
    <nav aria-label="Navegação principal" className="hidden bg-gov-teal xl:block"><ul className="container-espp flex h-14 items-stretch gap-1">{nav.map((item,i)=>{const sub="submenu" in item,ext="external" in item&&item.external,open=sub&&submenu===item.label,active=sub?item.submenu.some(s=>"href" in s&&pathname===s.href):pathname===item.href,c=`flex h-full items-center gap-1 px-3 py-3 text-[.75rem] font-semibold whitespace-nowrap uppercase transition-colors hover:bg-white/8 hover:text-gold-500 ${active?"bg-white/10 text-gold-500":"text-white"}`;return <li key={item.label} data-submenu={sub?"":undefined} className="relative shrink-0" onMouseEnter={sub?()=>setSubmenu(item.label):undefined} onMouseLeave={sub?()=>setSubmenu(null):undefined}>{sub?<button type="button" onClick={()=>setSubmenu(open?null:item.label)} className={c}>{item.label}<ChevronDown className={`size-3.5 ${open?"rotate-180":""}`}/></button>:ext?<a href={item.href} target="_blank" rel="noopener noreferrer" className={c}>{item.label}</a>:<Link href={item.href} className={c}>{item.label}</Link>}{sub&&<div className={`absolute top-full left-0 z-10 min-w-52 rounded-md border border-ink-200 bg-white py-2 shadow-lg ${open?"visible opacity-100":"invisible opacity-0"}`}>{item.submenu.map((s,j)=>"group" in s?<p key={j} className="px-4 pt-2.5 pb-1 text-[.65rem] font-bold tracking-[.16em] text-ink-400 uppercase">{s.group}</p>:"external" in s&&s.external?<a key={s.href} href={s.href} target="_blank" rel="noopener noreferrer" className="block px-4 py-2.5 text-xs font-semibold uppercase text-ink-700">{s.label}</a>:<Link key={s.href} href={s.href} className="block px-4 py-2.5 text-xs font-semibold uppercase text-ink-700">{"icone" in s?<Icon name={s.icone} className="mr-2 inline size-3.5"/>:null}{s.label}</Link>)}</div>}</li>})}</ul></nav>
    <div hidden={!aberto} className="max-h-[calc(100svh-var(--spacing-header))] overflow-y-auto border-t border-ink-200 bg-white xl:hidden"><nav className="container-espp py-6"><ul className="flex flex-col divide-y divide-ink-100">{nav.map(item=>{const sub="submenu" in item,ext="external" in item&&item.external;return <li key={item.label} className="py-1">{sub?<><p className="pt-3 text-sm font-semibold uppercase text-ink-900">{item.label}</p><ul className="pb-2 pl-4">{item.submenu.map((s,i)=>"group" in s?<li key={i} className="pt-3 pb-1 text-[.65rem] font-bold uppercase text-ink-400">{s.group}</li>:<li key={s.href}>{"external" in s&&s.external?<a href={s.href} target="_blank" rel="noopener noreferrer" className="block py-2.5 text-xs font-semibold uppercase text-ink-700">{s.label}</a>:<Link href={s.href} onClick={()=>setAberto(false)} className="block py-2.5 text-xs font-semibold uppercase text-ink-700">{s.label}</Link>}</li>)}</ul></>:ext?<a href={item.href} target="_blank" rel="noopener noreferrer" className="block py-3 text-sm font-semibold uppercase text-ink-900">{item.label}</a>:<Link href={item.href} onClick={()=>setAberto(false)} className="block py-3 text-sm font-semibold uppercase text-ink-900">{item.label}</Link>}</li>})}</ul></nav></div>
  </header>;
}
