apiVersion: v1
kind: ServiceAccount
metadata:
  name: espp-api
  namespace: espp
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espp-app
  namespace: espp
automountServiceAccountToken: false
