import type { Metadata } from "next";
import Link from "next/link";
import { LogIn, ShieldCheck } from "lucide-react";
import { LoginForm } from "@/components/admin/login-form";
import { site } from "@/content/site";
import { autenticacaoSspConfigurada } from "@/lib/auth/ssp";
export const metadata:Metadata={title:"Acesso administrativo",robots:{index:false,follow:false}};
const mensagensSsp:Record<string,string>={indisponivel:"A integração SSP ainda não está configurada neste ambiente.","retorno-invalido":"Não foi possível validar o retorno da autenticação institucional. Inicie o acesso novamente.","nao-integrado":"A comunicação de retorno da SSP está preparada, mas a identificação do usuário depende do contrato oficial de integração."};
export default async function LoginPage({searchParams}:{searchParams:Promise<{proximo?:string;ssp?:string}>}){const{proximo,ssp}=await searchParams;const configurada=autenticacaoSspConfigurada();const local=process.env.NODE_ENV!=="production"&&process.env.ESPP_AUTH_MODE?.trim().toLowerCase()==="local";const seguro=proximo?.startsWith("/admin")&&!proximo.startsWith("//")?proximo:undefined;const query=seguro?`?proximo=${encodeURIComponent(seguro)}`:"";return <div className="flex min-h-screen items-center justify-center bg-ink-900 px-5 py-12"><div className="w-full max-w-md"><div className="mb-6 flex flex-col items-center"><img src="/images/logo-espp-white.png" alt="ESPP — Escola Superior de Polícia Penal" className="h-16 w-auto max-w-[15rem] object-contain"/><span className="mt-2 text-[0.65rem] font-semibold tracking-[0.16em] text-ink-400 uppercase">Painel administrativo</span></div><div className="rounded-xl border border-ink-200 bg-white p-7 shadow-lg"><div className="mb-4 flex items-center gap-2 text-gov-teal"><ShieldCheck className="size-5"/><span className="text-[0.65rem] font-black tracking-[0.14em] uppercase">Acesso institucional</span></div><h1 className="title-display text-2xl text-ink-900">Acesso administrativo</h1><p className="mt-1.5 text-sm leading-6 text-ink-600">A entrada no painel utiliza a identidade institucional da SSP-GO e as permissões atribuídas ao usuário.</p>{ssp&&mensagensSsp[ssp]?<p role="alert" className="mt-5 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-xs font-semibold leading-5 text-amber-900">{mensagensSsp[ssp]}</p>:null}<Link href={`/admin/auth/ssp${query}`} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-md bg-gov-teal px-6 py-3 text-xs font-bold tracking-wide text-white uppercase transition hover:brightness-95"><LogIn className="size-4"/>Entrar com SSP</Link>{!configurada?<p className="mt-3 text-center text-xs leading-5 text-ink-500">Integração aguardando os endpoints e credenciais oficiais da SSP-GO.</p>:null}{local?<div className="mt-6 border-t border-ink-200 pt-5"><p className="mb-4 rounded-lg border border-gov-blue/15 bg-gov-blue/5 px-4 py-3 text-xs leading-5 text-ink-700">Modo local de desenvolvimento/homologação. Não é disponibilizado em produção.</p><LoginForm proximo={seguro}/></div>:null}</div><div className="mt-6 flex items-center justify-center gap-4 text-xs text-ink-400"><Link href="/acessos" className="underline underline-offset-4 hover:text-white">Central de acessos</Link><span>•</span><Link href="/" className="underline underline-offset-4 hover:text-white">Site da {site.sigla}</Link></div></div></div>}
