"use client";
import { Check, CircleAlert, Info, TriangleAlert, X } from "lucide-react";
import { createContext, useCallback, useContext, useMemo, useRef, useState, type ReactNode } from "react";
export type ToastKind = "success" | "error" | "warning" | "info";
type ToastInput = { title?: string; message: string; kind?: ToastKind; duration?: number };
type ToastItem = Required<Pick<ToastInput, "message" | "kind" | "duration">> & { id: number; title?: string };
type ToastContextValue = { showToast: (input: ToastInput) => number; dismissToast: (id: number) => void };
const ToastContext = createContext<ToastContextValue | null>(null);
const severity = { success: { icon: Check, title: "Sucesso", root: "border-[#22c55e] bg-[rgb(240_253_244_/_0.96)]", iconWrap: "text-[#16a34a]" }, error: { icon: CircleAlert, title: "Erro", root: "border-[#ef4444] bg-[rgb(254_242_242_/_0.96)]", iconWrap: "text-[#dc2626]" }, warning: { icon: TriangleAlert, title: "Atenção", root: "border-[#f97316] bg-[rgb(255_247_237_/_0.96)]", iconWrap: "text-[#ea580c]" }, info: { icon: Info, title: "Informação", root: "border-[#3b82f6] bg-[rgb(239_246_255_/_0.96)]", iconWrap: "text-[#2563eb]" } } satisfies Record<ToastKind, { icon: typeof Check; title: string; root: string; iconWrap: string }>;
export function ToastProvider({ children }: { children: ReactNode }) { const [toasts,setToasts]=useState<ToastItem[]>([]);const nextId=useRef(1);const timers=useRef(new Map<number,number>());const dismissToast=useCallback((id:number)=>{const timer=timers.current.get(id);if(timer)window.clearTimeout(timer);timers.current.delete(id);setToasts(current=>current.filter(item=>item.id!==id))},[]);const showToast=useCallback((input:ToastInput)=>{const id=nextId.current++,kind=input.kind??"info",duration=Math.max(input.duration??4500,1200);setToasts(current=>[...current,{id,kind,duration,title:input.title,message:input.message}].slice(-4));const timer=window.setTimeout(()=>{timers.current.delete(id);setToasts(current=>current.filter(item=>item.id!==id))},duration);timers.current.set(id,timer);return id},[]);const value=useMemo(()=>({showToast,dismissToast}),[showToast,dismissToast]);return <ToastContext.Provider value={value}>{children}<div className="pointer-events-none fixed inset-x-3 top-[calc(3.9rem+env(safe-area-inset-top))] z-[1000] flex flex-col gap-2 md:inset-x-auto md:top-5 md:right-5 md:w-[min(26rem,calc(100vw-2rem))] md:gap-3" aria-live="polite">{toasts.map(item=>{const visual=severity[item.kind],Icon=visual.icon;return <div key={item.id} role={item.kind==="error"?"alert":"status"} data-kind={item.kind} className={`toast-severity pointer-events-auto relative overflow-hidden rounded-2xl border shadow-md md:rounded-md ${visual.root}`}><div className="flex items-start gap-2.5 px-3.5 py-3 pr-10 md:gap-3 md:px-4 md:py-3.5 md:pr-11"><span className={`mt-0.5 inline-flex size-6 shrink-0 items-center justify-center ${visual.iconWrap}`}><Icon className="size-5" strokeWidth={2}/></span><div className="min-w-0 flex-1"><p className="text-sm font-bold leading-5 text-slate-900 md:text-[0.95rem] md:font-semibold">{item.title??visual.title}</p><p className="mt-0.5 text-xs leading-5 text-slate-700 md:mt-1 md:text-sm">{item.message}</p></div></div><button type="button" onClick={()=>dismissToast(item.id)} aria-label="Fechar mensagem" className="absolute top-2.5 right-2.5 inline-flex size-7 items-center justify-center rounded-md text-slate-600 transition-colors hover:bg-black/5 hover:text-slate-900"><X className="size-4"/></button></div>})}</div></ToastContext.Provider>}
export function useToast(){const context=useContext(ToastContext);if(!context)throw new Error("useToast deve ser usado dentro de ToastProvider.");return context}
