apiVersion: v1
kind: Secret
metadata:
  name: espp-secrets
  namespace: espp
type: Opaque
stringData:
  ESPP_DB_URL: "jdbc:oracle:thin:@//oracle.exemplo.interno:1521/SERVICO"
  ESPP_DB_USERNAME: "ESPP"
  ESPP_DB_PASSWORD: "ALTERAR"
  ESPP_CONFIG_ENCRYPTION_KEY: "ALTERAR"
  ESPP_MAIL_HOST: "ALTERAR"
  ESPP_MAIL_USERNAME: "ALTERAR"
  ESPP_MAIL_PASSWORD: "ALTERAR"
  ESPP_MAIL_TO: "ALTERAR"
