package br.gov.go.ppgo.espp.controller;
import br.gov.go.ppgo.espp.domain.*; import br.gov.go.ppgo.espp.repository.*; import br.gov.go.ppgo.espp.service.SlugService; import jakarta.persistence.EntityNotFoundException; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController public class ConteudoController {
 private final NoticiaRepository noticias; private final EventoRepository eventos; private final AtoNormativoRepository atos; private final SlugService slug;
 public ConteudoController(
     NoticiaRepository noticias,
     EventoRepository eventos,
     AtoNormativoRepository atos,
     SlugService slug
 ) {
     this.noticias = noticias;
     this.eventos = eventos;
     this.atos = atos;
     this.slug = slug;
 }
 public record NoticiaReq(@NotBlank String titulo,@NotNull LocalDate data,@NotBlank String categoria,@NotBlank String resumo,@NotBlank String conteudo,String imagemUrl,String imagemAlt,@NotNull StatusPublicacao status){}
 public record EventoReq(@NotBlank String titulo,@NotNull LocalDate dataInicio,LocalDate dataFim,String horario,String local,@NotBlank String modalidade,@NotBlank String categoria,@NotBlank String resumo,@NotBlank String conteudo,String imagemUrl,String imagemAlt,String inscricaoHref,@NotNull StatusPublicacao status){}
 public record AtoReq(@NotBlank String tipo,@NotBlank String numero,@NotBlank String titulo,@NotBlank String ementa,@NotBlank String situacao,@NotNull LocalDate data,String href,String anexoNome,String anexoUrl,Long anexoTamanho,@NotNull StatusPublicacao status){}
 @GetMapping("/api/v1/public/noticias") List<Noticia> pubNoticias(){return noticias.findByStatusOrderByDataDesc(StatusPublicacao.PUBLICADO);} @GetMapping("/api/v1/public/noticias/{s}") Noticia pubNoticia(@PathVariable String s){return noticias.findBySlug(s).filter(n->n.getStatus()==StatusPublicacao.PUBLICADO).orElseThrow(EntityNotFoundException::new);}
 @GetMapping("/api/v1/public/eventos") List<Evento> pubEventos(){return eventos.findByStatusOrderByDataInicioDesc(StatusPublicacao.PUBLICADO);} @GetMapping("/api/v1/public/eventos/{s}") Evento pubEvento(@PathVariable String s){return eventos.findBySlug(s).filter(e->e.getStatus()==StatusPublicacao.PUBLICADO).orElseThrow(EntityNotFoundException::new);}
 @GetMapping("/api/v1/public/atos-normativos") List<AtoNormativo> pubAtos(){return atos.findByStatusOrderByDataDesc(StatusPublicacao.PUBLICADO);}
 @GetMapping("/api/v1/admin/noticias") List<Noticia> noticias(){return noticias.findAllByOrderByDataDesc();} @PostMapping("/api/v1/admin/noticias") @ResponseStatus(HttpStatus.CREATED) Noticia cria(@Valid @RequestBody NoticiaReq r,Authentication a){var n=new Noticia(); noticia(n,r); n.setSlug(slug.unico(r.titulo(),noticias::existsBySlug)); n.setAutor(a.getName()); return noticias.save(n);} @PutMapping("/api/v1/admin/noticias/{id}") Noticia edita(@PathVariable String id,@Valid @RequestBody NoticiaReq r){var n=noticias.findById(id).orElseThrow(EntityNotFoundException::new); if(!n.getTitulo().equals(r.titulo()))n.setSlug(slug.unico(r.titulo(),noticias::existsBySlug)); noticia(n,r); return noticias.save(n);} @DeleteMapping("/api/v1/admin/noticias/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delN(@PathVariable String id){noticias.deleteById(id);}
 @GetMapping("/api/v1/admin/eventos") List<Evento> eventos(){return eventos.findAllByOrderByDataInicioDesc();} @PostMapping("/api/v1/admin/eventos") @ResponseStatus(HttpStatus.CREATED) Evento cria(@Valid @RequestBody EventoReq r,Authentication a){var e=new Evento(); evento(e,r); e.setSlug(slug.unico(r.titulo(),eventos::existsBySlug)); e.setAutor(a.getName()); return eventos.save(e);} @PutMapping("/api/v1/admin/eventos/{id}") Evento edita(@PathVariable String id,@Valid @RequestBody EventoReq r){var e=eventos.findById(id).orElseThrow(EntityNotFoundException::new); if(!e.getTitulo().equals(r.titulo()))e.setSlug(slug.unico(r.titulo(),eventos::existsBySlug)); evento(e,r); return eventos.save(e);} @DeleteMapping("/api/v1/admin/eventos/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delE(@PathVariable String id){eventos.deleteById(id);}
 @GetMapping("/api/v1/admin/atos-normativos") List<AtoNormativo> atos(){return atos.findAllByOrderByDataDesc();} @PostMapping("/api/v1/admin/atos-normativos") @ResponseStatus(HttpStatus.CREATED) AtoNormativo cria(@Valid @RequestBody AtoReq r,Authentication a){var x=new AtoNormativo(); ato(x,r); x.setAutor(a.getName()); return atos.save(x);} @PutMapping("/api/v1/admin/atos-normativos/{id}") AtoNormativo edita(@PathVariable String id,@Valid @RequestBody AtoReq r){var x=atos.findById(id).orElseThrow(EntityNotFoundException::new); ato(x,r); return atos.save(x);} @DeleteMapping("/api/v1/admin/atos-normativos/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delA(@PathVariable String id){atos.deleteById(id);}
 private void noticia(Noticia n,NoticiaReq r){n.setTitulo(r.titulo());n.setData(r.data());n.setCategoria(r.categoria());n.setResumo(r.resumo());n.setConteudo(r.conteudo());n.setImagemUrl(r.imagemUrl());n.setImagemAlt(r.imagemAlt());n.setStatus(r.status());}
 private void evento(Evento e,EventoReq r){e.setTitulo(r.titulo());e.setDataInicio(r.dataInicio());e.setDataFim(r.dataFim());e.setHorario(r.horario());e.setLocal(r.local());e.setModalidade(r.modalidade());e.setCategoria(r.categoria());e.setResumo(r.resumo());e.setConteudo(r.conteudo());e.setImagemUrl(r.imagemUrl());e.setImagemAlt(r.imagemAlt());e.setInscricaoHref(r.inscricaoHref());e.setStatus(r.status());}
 private void ato(AtoNormativo x,AtoReq r){x.setTipo(r.tipo());x.setNumero(r.numero());x.setTitulo(r.titulo());x.setEmenta(r.ementa());x.setSituacao(r.situacao());x.setData(r.data());x.setAno(r.data().getYear());x.setHref(r.href());x.setAnexoNome(r.anexoNome());x.setAnexoUrl(r.anexoUrl());x.setAnexoTamanho(r.anexoTamanho());x.setStatus(r.status());}
}